name: re_schedule
description: Re课表 - 离线导入 Excel/PDF 的移动课表
publish_to: none
version: 1.0.4+5

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  archive: ^4.0.9
  file_picker: ^12.2.0
  path: ^1.9.1
  pdfrx: ^2.6.1
  sqflite: ^2.4.3
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
